# Generated by Django 3.2.3 on 2021-07-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256, unique=True)),
                ('date', models.CharField(max_length=256)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('fakenews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fakenews.fakenews')),
                ('link_class', models.CharField(max_length=120)),
                ('date_type', models.CharField(choices=[('1', 'Id'), ('2', 'Class')], max_length=1)),
                ('date_id', models.CharField(max_length=120)),
                ('body_class', models.CharField(blank=True, max_length=120, null=True)),
            ],
            bases=('fakenews.fakenews',),
        ),
        migrations.CreateModel(
            name='Wordpress',
            fields=[
                ('fakenews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fakenews.fakenews')),
                ('post_type', models.CharField(default='', max_length=120)),
                ('domain', models.CharField(default='', max_length=120)),
            ],
            bases=('fakenews.fakenews',),
        ),
        migrations.AddField(
            model_name='fakenews',
            name='posts',
            field=models.ManyToManyField(blank=True, to='fakenews.Post'),
        ),
    ]
