# Generated by Django 3.2.3 on 2021-07-12 18:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0002_post_fake_news_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fake_news_source',
        ),
        migrations.AddField(
            model_name='post',
            name='fake_news_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=[], null=True, size=None),
        ),
    ]
