# Generated by Django 3.2.3 on 2021-07-12 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0003_auto_20210712_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fake_news_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=dict, null=True, size=None),
        ),
    ]
