# Generated by Django 3.1.4 on 2021-04-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('created_at', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=120)),
                ('profile_image_url', models.TextField()),
                ('protected', models.BooleanField()),
                ('public_metrics', models.TextField()),
                ('url', models.TextField()),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('conversation_id', models.TextField()),
                ('created_at', models.TextField()),
                ('lang', models.CharField(max_length=5)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.user')),
            ],
        ),
    ]
