# Generated by Django 3.2.3 on 2021-07-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=120, null=True, unique=True)),
                ('text', models.TextField()),
                ('conversation_id', models.TextField()),
                ('created_at', models.TextField()),
                ('lang', models.CharField(max_length=5, null=True)),
                ('text_type', models.CharField(choices=[('1', 'Fake'), ('2', 'True'), ('3', 'Unknown')], default='3', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('created_at', models.TextField()),
                ('description', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('profile_image_url', models.TextField()),
                ('protected', models.BooleanField()),
                ('public_metrics', models.TextField()),
                ('url', models.TextField()),
                ('verified', models.BooleanField()),
                ('tweets', models.ManyToManyField(blank=True, to='twitter.Tweet')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='twitter.user'),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, unique=True)),
                ('tweets', models.ManyToManyField(blank=True, to='twitter.Tweet')),
            ],
        ),
    ]
