# Generated by Django 3.1.4 on 2021-04-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20210413_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
