# Generated by Django 3.2.3 on 2021-09-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_remove_tweet_text_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='percentage',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='spreader',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
