# Generated by Django 3.2.3 on 2021-09-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20210920_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='text',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
