# Generated by Django 3.1.4 on 2021-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20210503_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='query',
            name='tweet_id',
        ),
        migrations.AddField(
            model_name='query',
            name='tweets',
            field=models.ManyToManyField(blank=True, null=True, to='twitter.Tweet'),
        ),
    ]
