# Generated by Django 3.1.4 on 2021-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20210503_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='tweets',
            field=models.ManyToManyField(blank=True, to='twitter.Tweet'),
        ),
    ]
