# Generated by Django 3.1.4 on 2021-03-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpress',
            name='postType',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='wordpress',
            name='url',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
