# Generated by Django 3.1.4 on 2021-03-29 13:32

from django.db import migrations, models
import wordpress.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0002_auto_20210324_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpress',
            name='domain',
            field=models.CharField(default='', max_length=120),
        ),
    ]
