# Generated by Django 3.1.4 on 2021-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0004_auto_20210329_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpress',
            name='domain',
            field=models.TextField(default='', max_length=120),
        ),
    ]
