# Generated by Django 3.1.4 on 2021-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0005_auto_20210329_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpress',
            name='domain',
            field=models.CharField(default='', max_length=120),
        ),
    ]
