# Generated by Django 3.1.4 on 2021-04-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0006_auto_20210329_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('link', models.CharField(max_length=120, unique=True)),
                ('date', models.CharField(max_length=120)),
                ('title', models.CharField(default='', max_length=120)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='wordpress',
            old_name='postType',
            new_name='post_type',
        ),
        migrations.AddField(
            model_name='wordpress',
            name='posts',
            field=models.ManyToManyField(blank=True, to='wordpress.Post'),
        ),
    ]
