# Generated by Django 3.1.4 on 2021-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0007_auto_20210421_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='external_id',
            field=models.CharField(max_length=120),
        ),
    ]
