# Generated by Django 3.1.4 on 2021-05-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0008_auto_20210426_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='external_id',
        ),
    ]
