# Generated by Django 3.1.4 on 2021-03-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('linkId', models.CharField(max_length=120)),
                ('dateType', models.CharField(max_length=120)),
                ('dateId', models.CharField(max_length=120)),
            ],
        ),
    ]
