# Generated by Django 3.1.4 on 2021-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soup',
            old_name='linkId',
            new_name='linkClass',
        ),
        migrations.AlterField(
            model_name='soup',
            name='dateType',
            field=models.CharField(choices=[('1', 'Id'), ('2', 'Class')], max_length=1),
        ),
    ]
