# Generated by Django 3.1.4 on 2021-03-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0002_auto_20210317_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soup',
            name='url',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
