# Generated by Django 3.1.4 on 2021-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0003_auto_20210324_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120, unique=True)),
                ('date', models.CharField(max_length=120)),
                ('title', models.CharField(default='', max_length=120)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='soup',
            old_name='dateId',
            new_name='date_id',
        ),
        migrations.RenameField(
            model_name='soup',
            old_name='dateType',
            new_name='date_type',
        ),
        migrations.RenameField(
            model_name='soup',
            old_name='linkClass',
            new_name='link_class',
        ),
        migrations.AddField(
            model_name='soup',
            name='posts',
            field=models.ManyToManyField(blank=True, to='soup.Post'),
        ),
    ]
